# Generated by Django 5.2.1 on 2025-05-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genova', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='Service',
        ),
    ]
