# Generated by Django 5.1.4 on 2026-01-30 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genova', '0002_rename_services_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partenaire_logo/')),
                ('site_web', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Code ISO (ex: FR, SN)', max_length=10)),
                ('drapeau', models.ImageField(upload_to='pays_drapeau/')),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Pays',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='visa_images/')),
                ('titre', models.CharField(blank=True, help_text='Titre indicatif ou description courte', max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='genova.pays')),
            ],
            options={
                'ordering': ['ordre', 'titre'],
            },
        ),
    ]
